name: Test Artifact Upload and Download

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test data" > testfile.txt
      - uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: testfile.txt

  download:
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: test-artifact
          path: ./downloaded
      - run: ls -l ./downloaded
      - run: cat ./downloaded/testfile.txt
